# Generated by Django 3.1.6 on 2021-02-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.CharField(max_length=255, verbose_name='Содержание')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_editing', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('activity_flag', models.CharField(max_length=20, verbose_name='Флаг активности')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('text_comment', models.CharField(max_length=255, verbose_name='Текст коментария')),
                ('news', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='newss.news', verbose_name='Новость')),
            ],
        ),
    ]
